---

- name: Add MariaDB yum repository
  template: src=MariaDB.repo.j2 dest=/etc/yum.repos.d/mariadb.repo

- name: Install MariaDB packages
  yum: name=mariadb-server state=installed

- name: Install MySQL-python
  yum: name=MySQL-python state=installed

- name: Create MariaDB configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - Restart mariadb

- name: Create MariaDB log file
  file: path={{ mysql_log }} state=touch owner=mysql group=mysql mode=0775

- name: Create MariaDB PID directory
  file: path={{ mysql_pid_dir }} state=directory owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mysql state=started enabled=yes
