---
#
# cm config files
#
- name: "update cloudera scm server option in cloudera-scm-agent config.ini file"
  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp='^server_host=.*' line="server_host={{ cm_remote_server | regex_replace('-ext', '') }}" owner=root group=root mode=0755 state=present backup=yes
  notify: restart cloudera-scm-agent
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
    - create-cluster
    - bare-cloudera


#- name: "update cloudera scm listening_hostname option in cloudera-scm-agent config.ini file"
#  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp='^# listening_hostname=.*' line="listening_hostname={{ inventory_hostname }}" owner=root group=root mode=0755 state=present backup=yes
#  when: is_cloud_node
#  notify: restart cloudera-scm-agent
#  tags:
#    - deploy-cm-agent
#    - install-cloudera-manager-agent
#    - create-cluster

- name: "update /usr/sbin/cmf-agent ulimit nofiles setting"
  lineinfile: dest=/usr/sbin/cmf-agent regexp='^ulimit -n (\d+)' line='ulimit -n 1024000' owner=root group=root mode=0755 state=present backup=yes
  notify: restart cloudera-scm-agent
  when: cm_major_version < 6
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
    - create-cluster

- name: "update /usr/sbin/cmf-agent ulimit nproc setting"
  lineinfile: dest=/usr/sbin/cmf-agent regexp='^ulimit -u (\d+)' line='ulimit -u 1024000' owner=root group=root mode=0755 state=present backup=yes
  notify: restart cloudera-scm-agent
  when: cm_major_version < 6
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
    - create-cluster

- name: "update cmf /usr/lib64/cmf/service/hbase/hbase.sh ulimit nofiles setting - RedHat"
  lineinfile: dest=/usr/lib64/cmf/service/hbase/hbase.sh regexp='ulimit -n (\d+)' line='ulimit -n 1024000' owner=root group=root mode=0755 state=present backup=yes
  notify: restart cloudera-scm-agent
  when: cm_major_version < 6 and (ansible_facts.os_family == 'RedHat' or ansible_facts.os_family == 'Suse')
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
    - create-cluster

- name: "update cmf /usr/lib/cmf/service/hbase/hbase.sh ulimit nofiles setting - Debian"
  lineinfile: dest=/usr/lib/cmf/service/hbase/hbase.sh regexp='ulimit -n (\d+)' line='ulimit -n 1024000' owner=root group=root mode=0755 state=present backup=yes
  notify: restart cloudera-scm-agent
  when: cm_major_version < 6 and ansible_facts.os_family == 'Debian'
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
    - create-cluster

- name: "enable and start cloudera manager agent service"
  service: name=cloudera-scm-agent state=started enabled=yes
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
    - create-cluster
    - start-cm-agent
    - create-cdh-cluster

- name: "Set usr_lib_path - RedHat"
  set_fact:
    usr_lib_path: /usr/lib64
  when: ansible_facts.os_family in ['RedHat', 'Suse']
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent

- name: "Set usr_lib_path - Debian"
  set_fact:
    usr_lib_path: /usr/lib
  when: ansible_facts.os_family == 'Debian'
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent

- name: "Check for graceful_stop_role.sh"
  stat: path={{usr_lib_path}}/cmf/service/csd/graceful_stop_role.sh
  register: graceful_stop
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent

- name: "Fix graceful_stop_role.sh perms"
  file: path={{usr_lib_path}}/cmf/service/csd/graceful_stop_role.sh mode=0755
  when: graceful_stop.stat.exists
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent

- name: "Configure JAVA_HOME"
  lineinfile: line='export JAVA_HOME={{java_home}}' regexp='export JAVA_HOME' path=/etc/default/{{item}} create=yes state=present
  loop:
    - cloudera-scm-agent
    - bigtop-utils
  tags:
    - deploy-cm-agent
    - install-cloudera-manager-agent
