---

- name: Fix rc.sysinit
  copy: src=rc.sysinit dest=/etc/rc.d/rc.sysinit mode=0755 owner=root group=root
  when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version in ['5', '6']

- name: Remove lsblk. This can cause timeouts when gathering facts
  file: path=/bin/lsblk state=absent
