#!/usr/bin/env bash
## This will be run after the hosts have been created by Terraform.
## It will look at the current nodes in the resource group and add their name to /etc/ansible/hosts

resource_group=`cat var_values.tfvars | grep resource_group_name | awk '{print $3}' | awk -F'"' '{$0=$2}1'`
nodes_list=`az vm list -g $resource_group --query '[].{Name:name}' -o tsv`

echo "## Autogenerated ansible hosts file" > /etc/ansible/hosts

for i in $nodes_list;
do

echo [$i] >> /etc/ansible/hosts
publicIps=`az vm show -g $resource_group -n $i --show-details --query '{IP:publicIps}' -o tsv`
echo $publicIps >> /etc/ansible/hosts
done
cat /etc/ansible/hosts