---
- name: "Enable Yarn HA: Wait for no active commands"
  uri:
    url={{cm_api_uri}}/cm/commands
    user=admin
    password=admin
    status_code=200,204
    return_content=yes
  retries: 150
  delay: 3
  register: check_no_active
  until: check_no_active.json is defined and 'items' in check_no_active.json and check_no_active.json['items'] == []

- name: "Enable Yarn HA: Send command to Cloudera Manager"
  uri:
    url={{cm_api_uri}}/clusters/{{cdh_cluster_name}}/services/{{cdh_yarn_service_name}}/commands/enableRmHa
    user=admin
    password=admin
    method=POST
    body='{"newRmHostId":"{{standby_namenode}}","zkServiceName":"{{zookeeper_service_name}}"}'
    body_format=json
    status_code=200,204
    return_content=yes
  register: ha_command

- name: "Show Yarn HA command ouput"
  debug: var=ha_command
  when: debug

- name: "Check Yarn HA command was successful"
  fail: msg="Yarn HA command failed - {{ha_command.json['resultMessage']}}"
  when: ha_command.json is defined and 'success' in ha_command.json and not ha_command.json['success']

- name: "Wait for commands to complete"
  uri:
    url={{cm_api_uri}}/clusters/{{cdh_cluster_name}}/services/{{cdh_yarn_service_name}}/commands
    user=admin
    password=admin
    status_code=200,204
    return_content=yes
  retries: 200
  delay: 3
  register: check_no_active
  until: check_no_active.json is defined and 'items' in check_no_active.json and check_no_active.json['items'] == []
