---
- name: Ensure mysql is started
  service: name=mysqld state=started enabled=yes
  when: ansible_facts.os_family in ['Suse', 'RedHat'] and ansible_facts.distribution_major_version != '7'

- name: Ensure mysql is started (rhel 7)
  service: name=mariadb state=started enabled=yes
  when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == '7'

- name: Ensure mysql is started
  service: name=mysql state=restarted enabled=yes
  when: ansible_facts.os_family == 'Debian'

- name: Create hive database
  command: mysql -e "CREATE DATABASE hive" creates=/var/lib/mysql/hive

- name: Create hive user
  command: mysql -e "GRANT ALL PRIVILEGES ON hive.* TO 'hive'@'{{item}}' IDENTIFIED BY 'hivepass'"
  loop:
    - "%"
    - "{{hive_server}}"
    - localhost
