---

- hosts: cdh-all
  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: true
  gather_facts: yes
  roles:
    - { role: cdh, when: not is_running_parcels }
    - cloudera-manager-agent

- hosts: cdh-all
  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: true
  gather_facts: no
  roles:
    - cloudera-manager-server-prep

- hosts: cm
  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: true
  gather_facts: no
  roles:
    - cloudera-manager-server-deploy-parcel

- hosts: cdh-all
  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: true
  gather_facts: no
  roles:
    - cloudera-manager-agent-start

- hosts: cm
  become: yes
  become_user: root
  become_method: sudo
  any_errors_fatal: true
  gather_facts: no
  roles:
    - cloudera-license
    - cloudera-manager-server-complete

###
### HDFS HA
###
- import_playbook: enable-ha.yml

##
## kerberos setup
##
- import_playbook: kerberos.yml


